apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: t4ay8zuim-java-quarkus-gitops-repository
spec:
  url: https://github.com/chetna14manku-org/t4ay8zuim-java-quarkus-gitops